---
en:
  simple_form:
    hints:
      defaults:
        setting_default_content_type_html: When writing hops, assume they are written in raw HTML, unless specified otherwise
        setting_default_content_type_markdown: When writing hops, assume they are using Markdown for rich text formatting, unless specified otherwise
        setting_default_content_type_plain: When writing hops, assume they are plain text with no special formatting, unless specified otherwise (default koyu.space behavior)
        setting_default_language: The language of your hops can be detected automatically, but it's not always accurate
        setting_skin: Reskins the selected koyu.space flavour
    labels:
      defaults:
        setting_default_content_type: Default format for hops
        setting_default_content_type_html: HTML
        setting_default_content_type_markdown: Markdown
        setting_default_content_type_plain: Plain text
        setting_favourite_modal: Show confirmation dialog before favouriting (applies to Glitch flavour only)
        setting_hide_followers_count: Hide your followers count
        setting_skin: Skin
        setting_system_emoji_font: Use system's default font for emojis (applies to Glitch flavour only)
